### ISSUE TITLE
Initializing project repo

### ISSUE THREAD

**Issue by Zhang-Haipeng** [UBC-MDS/DSCI-532_group-203_Milestone3-4#1]
@cgostic @lori94  Hi guys, I've just created this repo for the milestone 3 & 4 and initialized it with these files and folders. Please check if there's anything missing (note that I didn't involve the previous `proposal`, `README`, `data files`, `codes` yet since we haven't fully decided whether to create an R version of our squirrel park yet).

**Comment by lori94** [comment]
Thank you Roc. We can discuss it tomorrow. I was trying to wrangle the data using R today for the squirrel but not sure if I got it correctly and we can discuss this with Cari tomorrow to see if it is possible to plot a similar map in R. @Zhang-Haipeng @cgostic

**Comment by cgostic** [comment]
Yes I've been testing out mapping in ggplot and I think we'll be able to remake our altair plot.
